### ISSUE TITLE
Scenario-based specification section

### ISSUE THREAD

**Issue by allegroCoder** [tuura/scenco-article#8]
Here, the meaning of scenario-based specifications should be discussed, together with some example:
  - [x] instruction set architectures
  - [x] process-mining traces
  - [x] analogue circuits like the buck controller

I am not sure if the section `scenario-based specification` will be embedded into the `Introduction` section or not.

**Comment by allegroCoder** [comment]
@snowleopard : Please, could you suggested me something that I can read about how the process-mining traces, that we have used in the benchmarks, have been extracted, or where they come from. I think we need to mention something about this in the article.

**Comment by snowleopard** [comment]
@allegroCoder Great! The paper Jonny gave you is exactly what I was going to send you. It has all the necessary background material for understanding how process mining works. Happy to help if you have any questions.
